### ISSUE TITLE
Logitech K380 multimedia keys not working

### ISSUE THREAD

**Issue by Hamberthm** [turgu1/bt-keyboard#7]
Hi there!

I wanted to open this issue in regard to your issue report in ESPRESSIDF (https://github.com/espressif/esp-idf/issues/8318).

I have the same keyboard as you, and while trying to add multimedia key support to my project BT2PS2, I found multimedia keys would produce the same error you reported that time:

> E (430732) BT_HIDH: Not find report handle: 0 mode: REPORT

I've done a new report you can found here: https://github.com/espressif/esp-idf/issues/14259

This is an issue with ESPRESSIDF, I didn't test it with your code but I assumed it's the same story.  If you can test it to confirm, great.

Kind regards
Humberto

**Comment by Hamberthm** [comment]
It has been fixed by ESPRESSIF for future ESP-IDF releases via https://github.com/espressif/esp-idf/commit/06b2276b7f430047b823a0eebda97264c8ae87b7

I think you should decide if closing this or not, just to let people be aware that multimedia keys will not work with an K380 until future versions of the stack.

Cheers!

**Comment by turgu1** [comment]
Hello Hamberthm, sorry for that way too long delay to answer. Regaining sometime to work on this as I need it for another project. You may find an update that I made to this project in support of ESP-IDF V5.4 . Function keys are working well there with the K380. Still need to add them to the get_ascii...() methods.

Still have an issue with my BLE keyboard (MX Keys Mini) that refuses to be re-connected. I did sent an issue on this to the Espressif developpers.
